Repository Hacktoberfest-2021/problem_solving, pull requests merged in 2021-10, with the labels that each got.

#2 Factorial Replacing Solve Using C#
  Factorial Replacing/C#/Program.cs
Labels: hacktoberfestaccepted, hacktoberfest-accepted

#4 Solved fibonnachi replacement
  Factorial Replacing/C++/FibonachiReplacement.cpp
Labels: hacktoberfest, hacktoberfestaccepted, hacktoberfest-accepted

#8 add python solution
  Factorial Replacing/Python/Pipfile
  Factorial Replacing/Python/fib.py
Labels: good first issue, hacktoberfest, hacktoberfestaccepted, hacktoberfest-accepted
